name: Test and Release
on:
  push:
    branches:
      - workflow

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
  
jobs:
  # Build the application and run unit tests
  build-and-test:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          java-version: '14'
          distribution: 'temurin'
      - name: Build
        run: |
          chmod u+x gradlew
          ./gradlew clean build
      - name: Run tests
        run: ./gradlew test
        
  release:
    needs:
      - build-and-test
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Create jar
        run: |
          chmod u+x gradlew
          ./gradlew shadowJar
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.1.3
        with:
          name: JavaFX demo
          path: ./build/libs/Template-all.jar

