on:
  push:
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

name: Create Release
permissions:
  contents: write
  
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
  
jobs:
  packaging:
    runs-on: macos-12
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Create jar
        run: |
          chmod u+x gradlew
          ./gradlew shadowJar
      - name: Package
        run: |
            jpackage --verbose @jpackage-arguments.cfg
      - name: Upload windows installer
        uses: actions/upload-artifact@v3.1.3
        with:
          name: installers
          path: |
            ./*.dmg
            ./*.exe
            ./*.deb
            
  create-release:
    needs: packaging
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Download installers
        uses: actions/download-artifact@v3
        with:
          name: installers
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            *.dmg
            *.exe
            *.deb
