on:
  push:
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

name: Create Release

jobs:
  packaging:
    strategy:
      matrix:
        os: [ windows-2022, macos-12, ubuntu-22.04 ]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Create jar
        run: |
          chmod u+x gradlew
          ./gradlew shadowJar
      - name: Package
        run: |
            jpackage --verbose @jpackage-arguments.cfg --app-version ${{ github.ref_name }}
      - name: Upload windows installer
        uses: actions/upload-artifact@v3.1.3
        with:
          name: installers
          path: |
            ./*.dmg
            ./*.exe
            ./*.deb
            
  create-relase:
    needs: packaging
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Download installers
      - uses: actions/download-artifact@v3
        with:
            path: ~/Downloads/
      - name: Release
      - uses: softprops/action-gh-release@v1
        with:
          files: ~/Downloads/*
            